# -*- coding: utf-8 -*-
"""cleaning_insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/thamyrissacamoto/MarvelAPI/blob/Thamyris%2FconsumindoAPI/cleaning_insights.ipynb
"""

import pandas as pd
import sqlite3
import ast
import matplotlib.pyplot as plt

characters = pd.read_csv('characters_raw.csv')

characters.columns

df_characters = characters[[
    'id', 'name', 'description', 'modified', 'comics.available',
    'comics.items', 'series.available', 'series.items', 'stories.available',
    'stories.items', 'events.available', 'events.items'
]].copy()

def parse(x):
    if x == x:
        return ast.literal_eval(x)
    return []

cols = ["comics", "series", "stories", "events"]

for c in cols:
    col_origem = f"{c}.items"
    col_destino = f"{c}_list"
    df_characters[col_destino] = df_characters[col_origem].apply(parse)

df_characters.drop(columns=["comics.items", "series.items", "stories.items", "events.items"], inplace=True)

df_characters.rename(columns={
    'comics.available': 'num_comics',
    'series.available': 'num_series',
    'stories.available': 'num_stories',
    'events.available': 'num_events',
}, inplace=True)

df_characters.drop(columns=["comics_list", "series_list", "stories_list", "events_list"]).duplicated()

df_characters['modified'] = pd.to_datetime(df_characters['modified'])

df_characters.dtypes

df_characters.head(2)

df_characters.describe()

df_characters.isnull().sum()

col = "description"
counts = df_characters[col].isna().value_counts().rename({True: "Nulos", False: "Não nulos"})

counts.plot(kind="bar", color=["salmon", "steelblue"])
plt.title(f"Valores nulos × não nulos em 'descrição'")
plt.ylabel("Quantidade")
plt.xlabel("Descrição")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

df_top_comics = df_characters[["name", "num_comics"]].sort_values(by="num_comics", ascending=False).head(10)

df_top_comics.plot(x='name', y='num_comics', kind='bar', title='Personagens mais Populares')
plt.legend(["Número de HQs"])
plt.xlabel('Personagem')
plt.ylabel('HQs');
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

from pathlib import WindowsPath
cols = ["num_comics", "num_series", "num_stories", "num_events"]
df_top = df_characters[["name"] + cols].sort_values(by="num_comics", ascending=False).head(10)

ax = df_top.set_index("name")[cols].plot(kind="bar", figsize=(15,6), width=1)
plt.title("Personagens mais Populares")
plt.ylabel("Quantidade")
plt.xlabel("Personagem")
plt.legend(["Número de HQs", "Número de Séries", "Número de Histórias", "Número de Eventos"])
plt.xticks(rotation=45, ha="right")

for barra in ax.patches:
    altura = barra.get_height()
    x = barra.get_x() + barra.get_width() / 2
    y = altura
    ax.text(x, y, str(int(altura)), ha='center', va='bottom')

plt.tight_layout()
plt.show()